services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    restart: always
    volumes:
      - ./domain:/api/domain
      - ./model:/api/model
      - ./dataset:/api/dataset
      - ./utils:/api/utils
